### ISSUE TITLE
Process stuck after scanning QR

### ISSUE THREAD

**Issue by Archehandoro** [icewind1991/matrix-puppet-signal-docker#1]
Hello,
After scanning QR the process is stuck at:

`INFO  2020-01-10T17:17:31.532Z SQL channel job 136 (createOrUpdateItem) succeeded in 27ms`

Also, where you mention:

> Generate signal-registration.yaml using docker run -it --rm -v $(pwd)/config.json:/conf/config.json icewind1991/matrix-puppet-signal registration "http://signal-bridge.example.com"

Do you mean we need to create a dns entry with signal-bridge.example.com pointing to the box that we are running the docker image? Or should it point to the bridge (let's say dimensions) that I currently have?

Thanks!

**Comment by Archehandoro** [comment]
Ok, if I understand correctly after scanning the QR the process can be exited and then generate the signal-registration.json. Which I do, and it returns some info for signal-registration.yaml, which it doesn't create anywhere. If I try to run the bridge, I get the following error:

`/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:227
      throw ex;
      ^

Error: ENOENT: no such file or directory, open 'signal-registration.yaml'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Cli._loadYaml (/matrix-puppet-signal/node_modules/matrix-appservice-bridge/lib/components/cli.js:188:29)
    at Cli._startWithConfig (/matrix-puppet-signal/node_modules/matrix-appservice-bridge/lib/components/cli.js:183:48)
    at Cli.run (/matrix-puppet-signal/node_modules/matrix-appservice-bridge/lib/components/cli.js:140:10)
    at Object.<anonymous> (/matrix-puppet-signal/index.js:365:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)`

**Comment by Archehandoro** [comment]
The issue here was that the docker image searches for signal-registration.yaml but .json was set on the command to run the image.
