### ISSUE TITLE
Not available to send messages from Matrix

### ISSUE THREAD

**Issue by Archehandoro** [icewind1991/matrix-puppet-signal-docker#2]
Hello,

I've managed to make it work... sort of. I can receive messages, see groups and chats on Matrix. But I can't send messages from Matrix to Signal. I get this error:
`Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { successfulNumbers: [],
    failoverNumbers: [],
    errors: [ [Error] ],
    unidentifiedDeliveries: [] } }  reason:  { successfulNumbers: [],
  failoverNumbers: [],
  errors:
   [ { Error: Illegal value for Message.Field .signalservice.Content.syncMessage: .signalservice.SyncMessage (Error: Illegal value for Message.Field .signalservice.SyncMessage.read: .signalservice.SyncMessage.Read (Error: Illegal value for Message.Field .signalservice.SyncMessage.Read.sender of type string: undefined (not a string)))
         at Field.ProtoBuf.Reflect.FieldPrototype.encode (/matrix-puppet-signal/node_modules/signal-desktop/components/protobuf/dist/ProtoBuf.js:2811:27)
         at Message.ProtoBuf.Reflect.MessagePrototype.encode (/matrix-puppet-signal/node_modules/signal-desktop/components/protobuf/dist/ProtoBuf.js:2342:31)
         at MessagePrototype.encode (/matrix-puppet-signal/node_modules/signal-desktop/components/protobuf/dist/ProtoBuf.js:1981:31)
         at MessagePrototype.encodeAB (/matrix-puppet-signal/node_modules/signal-desktop/components/protobuf/dist/ProtoBuf.js:2034:41)
         at OutgoingMessage.getPlaintext (/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:39973:42)
         at OutgoingMessage.doSendMessage (/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:39985:28)
         at textsecure.storage.protocol.getDeviceIds.then.deviceIds (/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:39812:21)
         at process._tickCallback (internal/process/next_tick.js:68:7)
       number: 'MyRealPhoneNumberHere',
       reason:
        'Failed to retrieve new device keys for number MyRealPhoneNumberHere' } ],
  unidentifiedDeliveries: [] }`

Any ideas? Thanks!

**Comment by Archehandoro** [comment]
The problem was that the name of docker image wasn't matching the variable in signal-registration.yaml

**Comment by BobWs** [comment]
> The problem was that the name of docker image wasn't matching the variable in signal-registration.yaml

Can you please elaborate? I'm having the same problem. I can receive but I cannot sent. I the log I don't see anything that indicate to a problem.
